[package]
name = "carepanion-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "=1.18.26"
borsh = "1.5.1"
thiserror = "1.0"
bs58 = "0.5.1"

[dev-dependencies]
solana-program-test = "=1.18.26"
solana-sdk = "=1.18.26"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[features]
custom-heap = []
custom-panic = []
